### ISSUE TITLE
Ofelia Array won't reinitialize

### ISSUE THREAD

**Issue by emviveros** [cuinjune/Ofelia#37]
I'm start learning ofelia and and I came across the following behavior, initializing an array with ofArray in ofelia pd object I can't reduce the size of the array. See image below:

![resetArray_patch1](https://user-images.githubusercontent.com/3089536/89151219-da8f5c00-d536-11ea-99c0-8617f9c7a595.png)

And if I open another patch with diferent ofelia object name with the same variable name, the biggest array size persist:

![resetArray_patch2](https://user-images.githubusercontent.com/3089536/89151380-36f27b80-d537-11ea-905b-dbbd07b9bbdb.png)

I don't know if its a expected behavior.. Or is there another way to do that I didn't get..

These are the patches: [resetArraysIssuePatches.zip](https://github.com/cuinjune/Ofelia/files/5014205/resetArraysIssuePatches.zip)

Thanks! 

Pd 0.51 - OSx 10.13.6 High Sierra - Ofelia v3.1.0

**Comment by cuinjune** [comment]
Hi, I believe the `ofArray()` class is for interacting with the Pd's array. 
You can check out `examples/pd/misc/main.pd` example to learn how it can be used.

If you want to just use an array feature, use `ofTable()` instead which is identical to `{}` in Lua.
Here's a simple example object you can try:

```
ofelia f;
local t = ofTable(1, 2, 3);
return t;
```

**Comment by emviveros** [comment]
Thankks a lot!!!

The problem was misuse of ofArray().

Using ofTable() all works!! 

![patch1](https://user-images.githubusercontent.com/3089536/89210256-2ae9d680-d596-11ea-8619-77421070c605.png)

Thanks again for ofelia!
