### ISSUE TITLE
ofelia/scripts/ubuntu/install_dependencies.sh fail on Ubuntu 20.04

### ISSUE THREAD

**Issue by marcelo-queiroz** [cuinjune/Ofelia#38]
Hi there!

I'm trying to run ofelia 3.1.0 installed from decken on puredata 0.50.2 and Ubuntu 20.04. At some point of ofelia/scripts/ubuntu/install_dependencies.sh I get:

Installing libopencv-dev
E: Unable to correct problems, you have held broken packages.
error installing libopencv-dev
Reading package lists... Building dependency tree... Reading state information... Some packages could not be installed. This may mean that you have requested an impossible situation or if you are using the unstable distribution that some required packages have not yet been created or been moved out of Incoming. The following information may help to resolve the situation: The following packages have unmet dependencies: libopencv-dev : Depends: libopencv-calib3d-dev (= 4.2.0+dfsg-5) but it is not going to be installed Depends: libopencv-contrib-dev (= 4.2.0+dfsg-5) but it is not going to be installed Depends: libopencv-features2d-dev (= 4.2.0+dfsg-5) but it is not going to be installed Depends: libopencv-highgui-dev (= 4.2.0+dfsg-5) but it is not going to be installed Depends: libopencv-objdetect-dev (= 4.2.0+dfsg-5) but it is not going to be installed Depends: libopencv-stitching-dev (= 4.2.0+dfsg-5) but it is not going to be installed Depends: libopencv-superres-dev (= 4.2.0+dfsg-5) but it is not going to be installed Depends: libopencv-videoio-dev (= 4.2.0+dfsg-5) but it is not going to be installed Depends: libopencv-videostab-dev (= 4.2.0+dfsg-5) but it is not going to be installed
this seems an error with your distribution repositories but you can also
report an issue in the openFrameworks github: http://github.com/openframeworks/openFrameworks/issues

I did try to manually apt install these dependencies and their dependencies, by issuing 

sudo apt install libopencv-calib3d-dev libopencv-contrib-dev libopencv-features2d-dev libopencv-highgui-dev libopencv-objdetect-dev libopencv-stitching-dev libopencv-superres-dev libopencv-videoio-dev libopencv-videostab-dev libavresample-dev libswscale-dev

but I got

The following packages have unmet dependencies:
 libavresample-dev : Depends: libavutil-dev (= 7:4.2.4-1ubuntu0.1) but 7:4.3-2~18.04.york0 is to be installed
                     Depends: libavresample4 (= 7:4.2.4-1ubuntu0.1) but 7:4.3-2~18.04.york0 is to be installed
 libswscale-dev : Depends: libavutil-dev (= 7:4.2.4-1ubuntu0.1) but 7:4.3-2~18.04.york0 is to be installed
                  Depends: libswscale5 (= 7:4.2.4-1ubuntu0.1) but 7:4.3-2~18.04.york0 is to be installed
E: Unable to correct problems, you have held broken packages.

so I figured I should ask for help instead of downgrading many package versions on my system (without any a priori guarantee of success).

Thanks!

Marcelo

**Comment by cuinjune** [comment]
Could you please try downloading openFrameworks for Linux from https://openframeworks.cc/download/ and then try running the `of_v0.11.0_linux64gcc6_release/scripts/linux/ubuntu/install_dependencies.sh`?

**Comment by marcelo-queiroz** [comment]
Hi Zack! Thanks for your reply!

of_v0.11.0_linux64gcc6_release/scripts/linux/ubuntu/install_dependencies.sh
produces the same problem:

Installing libopencv-dev
E: Unable to correct problems, you have held broken packages.
error installing libopencv-dev
Reading package lists... Building dependency tree... Reading state
information... Some packages could not be installed. This may mean that you
have requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created or been
moved out of Incoming. The following information may help to resolve the
situation: The following packages have unmet dependencies: libopencv-dev :
Depends: libopencv-calib3d-dev (= 4.2.0+dfsg-5) but it is not going to be
installed Depends: libopencv-contrib-dev (= 4.2.0+dfsg-5) but it is not
going to be installed Depends: libopencv-features2d-dev (= 4.2.0+dfsg-5)
but it is not going to be installed Depends: libopencv-highgui-dev (=
4.2.0+dfsg-5) but it is not going to be installed Depends:
libopencv-objdetect-dev (= 4.2.0+dfsg-5) but it is not going to be
installed Depends: libopencv-stitching-dev (= 4.2.0+dfsg-5) but it is not
going to be installed Depends: libopencv-superres-dev (= 4.2.0+dfsg-5) but
it is not going to be installed Depends: libopencv-videoio-dev (=
4.2.0+dfsg-5) but it is not going to be installed Depends:
libopencv-videostab-dev (= 4.2.0+dfsg-5) but it is not going to be installed
this seems an error with your distribution repositories but you can also
report an issue in the openFrameworks github:
http://github.com/openframeworks/openFrameworks/issues

I'm not sure if there would be some problem with a previous version of
openFrameworks (0.10.1) that I had installed. I tried to find
uninstall instructions without success, but it seems that the OF
installation is self-contained, so maybe this has nothing to do with my
current problem.

Thanks!

Marcelo


Em seg., 3 de ago. de 2020 às 12:11, Zack Lee <notifications@github.com>
escreveu:

**Comment by marcelo-queiroz** [comment]
Not sure if it helps in any way: I try to "force" installation of the remaining dependencies by:

wget http://security.ubuntu.com/ubuntu/pool/universe/o/opencv/libopencv-dev_4.2.0+dfsg-5_amd64.deb
sudo dpkg -i libopencv-dev_4.2.0+dfsg-5_amd64.deb

This package gets installed but not configured. Then install_dependencies complains about librtaudio, so:

wget http://security.ubuntu.com/ubuntu/pool/universe/r/rtaudio/librtaudio-dev_5.0.0~ds-3build1_amd64.deb
sudo dpkg -i librtaudio-dev_5.0.0~ds-3build1_amd64.deb

Then install_dependencies manages to finish (with some broken packages).

In Pd, creating an [ofelia] object produces errors, which I tried to bypass with symbolic links:

.local/lib/pd/extra/ofelia/ofelia.pd_linux: libGLEW.so.2.0: cannot open shared object file: No such file or directory
.local/lib/pd/extra/ofelia/ofelia.pd_linux: libboost_filesystem.so.1.65.1: cannot open shared object file: No such file or directory
.local/lib/pd/extra/ofelia/ofelia.pd_linux: libboost_system.so.1.65.1: cannot open shared object file: No such file or directory

to which I tried to force using the available libraries:

sudo ln -s x86_64-linux-gnu/libGLEW.so.2.1 libGLEW.so.2.0
sudo ln -s x86_64-linux-gnu/libboost_filesystem.so.1.71.0 libboost_filesystem.so.1.65.1
sudo ln -s x86_64-linux-gnu/libboost_system.so.1.71.0 libboost_system.so.1.65.1

But then I got stuck with (in Pd trying to create [ofelia]):

.local/lib/pd/extra/ofelia/ofelia.pd_linux: /home/mqz/.local/lib/pd/extra/ofelia/ofelia.pd_linux: undefined symbol: _ZN5boost6system16generic_categoryEv

**Comment by marcelo-queiroz** [comment]
I finally solved it. Let me document what I did in case anyone else runs into the same problem.

I ran into two problems, not necessarily related: (1) install_dependencies not working in my system, and (2) ofelia dependence on older versions of libglew/libboost_filesystem/libboost_system (which are not available in Ubuntu 20.04).

1) the problem with install_dependencies.sh not finishing had to do with some ppa alternative repositories I had with conflicting libraries (libavutil-dev=7:4.3-2\~18.04.york0, libavresample4=7:4.3-2\~18.04.york0,libswscale5=7:4.3-2\~18.04.york0). To bring my system closer to a fresh install I removed all ppas (using [these tips](https://askubuntu.com/questions/148932/how-can-i-get-a-list-of-all-repositories-and-ppas-from-the-command-line-into-an) and [these tips](https://askubuntu.com/questions/307/how-can-ppas-be-removed)) and also removing all remaining unreferenced packages (using [this tip](https://ubuntuforums.org/showthread.php?t=224348)). Then install_dependencies and install_codecs both worked as expected.

2) ofelia (and probably openframeworks) depend on libglew2.0, libboost-filesystem1.65.1 and libboost-system1.65.1, but Ubuntu 20.4 comes with libglew2.1, libboost-filesystem1.71.0 and libboost-system1.71.0. To remedy this situation, I downloaded the required packages from Ubuntu 18.04 repos:

    wget https://packages.ubuntu.com/bionic/amd64/libglew2.0/download
    wget https://packages.ubuntu.com/bionic/amd64/libboost-filesystem1.65.1/download
    wget https://packages.ubuntu.com/bionic/amd64/libboost-system1.65.1/download
    sudo dpkg -i libboost-filesystem1.65.1_1.65.1+dfsg-0ubuntu5_amd64.deb libboost-system1.65.1_1.65.1+dfsg-0ubuntu5_amd64.deb libglew2.0_2.0.0-5_amd64.deb

Now things appear to be working. I hope these libraries won't conflict with other software.
