### ISSUE TITLE
about generating log messages in Pd console

### ISSUE THREAD

**Issue by emviveros** [cuinjune/Ofelia#46]
There's a way to customize log messages in pd console with [ofelia] object?

The intention is produce log error messages in pd console, in red color, like described in the session "Log messages and error" in [pd-Lua intro](https://agraef.github.io/pd-lua/tutorial/pd-lua-intro.html) by agraef

Thanks!

**Comment by cuinjune** [comment]
Yes, you can use the "ofLog()" class.

Try this:

```
ofelia f;
local log = ofLog();
log:post("Black message");
log:error("Red message");
```

**Comment by emviveros** [comment]
Wowsers!!!! Thank you a lot!!! :)
