### ISSUE TITLE
Need Ofelia Windows package without deken

### ISSUE THREAD

**Issue by jamshark70** [cuinjune/Ofelia#47]
Behind the Great Firewall of China, deken is painfully slow and not reliable. And the Ofelia package for Windows is large, will take literally at least an hour (if the connection doesn't drop in the middle).

I would like to download from github on my Linux machine (which has a vpn). But I see only ofxOfelia releases here.

How do I download Ofelia for Windows on a non-Windows machine?

**Comment by jamshark70** [comment]
Update: I tried deken again and it was a lot faster. So it's not urgent.

I'm thinking to use it in a course next fall semester. With 40 students, it's easier if I can just send a zip in case they have deken connectivity problems. Would it be possible to upload builds here as well (in that case, Mac and Win64)? Thanks.

**Comment by cuinjune** [comment]
Hi, Thank you for your suggestion.
I just uploaded them in the [Releases](https://github.com/cuinjune/Ofelia/releases/tag/v4.0.0).
You can download one of the files starting with "ofelia-v4.0.0-" and uncompress it to get the "ofelia" folder.

**Comment by jamshark70** [comment]
Fantastic, thanks! Can close this one.
