### ISSUE TITLE
Ofelia freezes PD 0.52.0test2

### ISSUE THREAD

**Issue by Jonathhhan** [cuinjune/Ofelia#66]
Tested with Windows 10 and Ubunu 20.04.
And often after freezing (without any error message) PD chrashes.
0.51.4 works absolutely fine with Ofelia.

**Comment by 60-hz** [comment]
Yes, it might be what I described here https://github.com/cuinjune/Ofelia/issues/65
It seems to be related to audio scheduling.

**Comment by Jonathhhan** [comment]
@60-hz yes, that seems to be the same issue.
