### ISSUE TITLE
Update ofxOfeliaLua for Lua 5.4.6

### ISSUE THREAD

**Issue by Jonathhhan** [cuinjune/Ofelia#85]
The updated `ofxLua` works with `ofxOfelia`, if I downgrade the included `Lua` to 5.3.6.
And I wonder how to change `ofxOfeliaLua.cpp` for make it work with `Lua` 5.4.6: https://github.com/cuinjune/Ofelia/blob/master/src/ofxOfeliaLua.cpp

**Comment by danomatika** [comment]
What is the actual issue beyond "it works with version A and not version B"? What do you mean by "works" or "doesn't work", there is not info if there is a build error, runtime, error etc...

**Comment by Jonathhhan** [comment]
@danomatika sorry, that was not clear. Sound is still there, but just a grey screen. Strangely there is no error message...

**Comment by danomatika** [comment]
Ok, I can't help with anything specific to Ofelia. I was thinking it's a build issue with ofxLua.

**Comment by Jonathhhan** [comment]
No, its specific to `Ofelia`. It just depends on the `Lua` lib that is included in `ofxPd`.

**Comment by Jonathhhan** [comment]
@cuinjune do you have any idea how to make `ofxOfelia` compatible with Lua 5.4.6 (current `ofxLua`)? Thanks.

**Comment by Jonathhhan** [comment]
This PR https://github.com/cuinjune/Ofelia/pull/86 seems to solve the issue.

**Comment by danomatika** [comment]
Another approach to this is to check the Lua version and conditionally define things that might have been removed: https://github.com/danomatika/ofxLua/blob/master/src/ofxLua.h#L34

Also, you can check if the define exists and define it if not.
